# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twoTumours_CaseB_TA <- function(n1, n2, delta, gamma1, gamma2, tau, max_samples = 10L) {
    .Call('tumour_twoTumours_CaseB_TA', PACKAGE = 'tumour', n1, n2, delta, gamma1, gamma2, tau, max_samples)
}

twoTumours_CaseB_TA_alt <- function(n1, n2, delta, gamma1, gamma2, tau, max_samples = 10L) {
    .Call('tumour_twoTumours_CaseB_TA_alt', PACKAGE = 'tumour', n1, n2, delta, gamma1, gamma2, tau, max_samples)
}

twoTumours_CaseB_TA_hybrid <- function(n1, n2, delta, gamma1, gamma2, tau, max_samples = 10L) {
    .Call('tumour_twoTumours_CaseB_TA_hybrid', PACKAGE = 'tumour', n1, n2, delta, gamma1, gamma2, tau, max_samples)
}

